/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-25 11:49:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class newEventErros_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"_Javascript/contact-us-js.js\"></script>     \r\n");
      out.write("        <link rel = \"stylesheet\" href=\"_css/style-pages.css\"/>\r\n");
      out.write("        <link rel = \"stylesheet\" href=\"_css/style-pattern-pages.css\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"block-principal\">\r\n");
      out.write("        <div id=\"conteiner-header\">\r\n");
      out.write("            <div id=\"logo\">\r\n");
      out.write("                <img src=\"_imagens/logo.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"name-site\">\r\n");
      out.write("                <h1>VamoLáVer</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"redes-sociais\">\r\n");
      out.write("                <img src=\"_imagens/redes-sociais.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"home-page.html\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"contact-us.html\">Quem Somos?</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"pontos-turisticos.html\">Pontos Turisticos</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"custon-search-page.html\">Busca Personalizada</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"#\">Meus Eventos</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <table id=\"drop-down\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <img alt=\"novo\" height=\"20px\" width=\"20px\" src=\"_imagens/add-png-black.png\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <a href=\"new-event.html\">Cadastrar Futuro evento</a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <img alt=\"favorito\" height=\"20px\" width=\"20px\" src=\"_imagens/star-favorite-black-png.png\">\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"favorite-events.html\">Meus Eventos Favoritos</a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <img alt=\"lista\" height=\"20px\" width=\"20px\" src=\"_imagens/list-icon-png-black.png\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <a href=\"edit-my-events.html\">Modificar evento já cadastrado</a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"search-box\">\r\n");
      out.write("                            <input type=\"text\" id=\"txt-search-box\" placeholder=\"...Buscar...\" size=\"20px;\"/>\r\n");
      out.write("                            <div id=\"pesquisar\">\r\n");
      out.write("                                <a href=\"search-result.html\">\r\n");
      out.write("                                    <img id=\"img-a\" src=\"_imagens/pesquisar.png\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a id=\"a-model-login\" onclick=\"gomodellogin()\">\r\n");
      out.write("                            LOGIN\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"only\">\r\n");
      out.write("                        <a href=\"sing-in.html\">\r\n");
      out.write("                            SING IN\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-content\">\r\n");
      out.write("            <div class=\"div-c\">\r\n");
      out.write("                ");

                List<String> erros = (ArrayList<String>) request.getAttribute("erros");	

                for(String s: erros){
                    out.println("<h1>"+s+"</h1>");
                }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer id=\"rodape\">\r\n");
      out.write("            <p>Copyright &copy; 2017 -André,Lucas,Nereida,Rafael</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <div id=\"modal-login\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content-login\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <span class=\"closel\">&times;</span>\r\n");
      out.write("                    <h3>Login</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <form name=\"login\">\r\n");
      out.write("                            <label for=\"login-username-email\">Email/Usuário</label>\r\n");
      out.write("                            <input type=\"text\" class=\"txts\" id=\"login-username-email\" size=\"30\">\r\n");
      out.write("                            <label for=\"login-user-password\">Senha</label>\r\n");
      out.write("                            <input type=\"password\" class=\"txts\" id=\"login-user-password\" size=\"30\">\r\n");
      out.write("                            <input type=\"submit\" class=\"submit-b\" id=\"btn-login-entrar\" value=\"Entrar\">\r\n");
      out.write("                            <a href=\"remember-password.html\">esqueceu a senha?</a>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
